export const SERVICES = [
  {
    id: 'ohs',
    icon: '🦺',
    title: 'Occupational Health & Safety',
    short: 'OHS',
    description: 'Comprehensive OHS solutions including risk assessment, safety audits, ISO 45001:2018 implementation, and behavioral safety programs.',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80',
    tags: ['HIRA', 'ISO 45001', 'JSA', 'Fire Safety'],
    features: [
      'OHS policy development and implementation support',
      'Workplace hazard identification and risk assessment (HIRA)',
      'Safety audits, inspections, and compliance reporting',
      'Job Safety Analysis (JSA) and Safe Work Procedure development',
      'Training on fire safety, confined space entry & emergency response',
      'ISO 45001:2018 systems implementation and internal auditing',
      'Safety culture enhancement and behavioral safety programs',
    ],
  },
  {
    id: 'energy',
    icon: '⚡',
    title: 'Energy Audit & Efficiency',
    short: 'Energy',
    description: 'Comprehensive energy audits identifying savings opportunities, renewable feasibility assessments, and EPRA compliance strategies.',
    image: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&q=80',
    tags: ['EPRA', 'Solar', 'Biomass', 'Waste-to-Energy'],
    features: [
      'Industrial, commercial, and institutional energy audits',
      'Identification of energy-saving opportunities and technology upgrades',
      'Renewable energy feasibility assessments (solar, biomass, waste-to-energy)',
      'Compliance with Energy (Energy Management) Regulations 2012 under EPRA',
      'Training on energy management and awareness creation',
    ],
  },
  {
    id: 'meal',
    icon: '📊',
    title: 'Monitoring, Evaluation & Learning',
    short: 'MEAL',
    description: 'MEAL frameworks, baseline studies, performance indicators, and digital dashboard-based systems for adaptive management.',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    tags: ['M&E Frameworks', 'Baselines', 'Dashboards', 'Impact Assessment'],
    features: [
      'Design of M&E frameworks and results chains',
      'Baseline, midterm, and endline evaluations',
      'Development of performance indicators and reporting tools',
      'Impact assessment and knowledge documentation',
      'Digital and dashboard-based M&E systems',
      'Training on M&E tools and adaptive learning',
    ],
  },
  {
    id: 'rap',
    icon: '🏘️',
    title: 'Resettlement Action Plans',
    short: 'RAP',
    description: 'RAP preparation, livelihood restoration frameworks, social impact assessments, and grievance redress mechanisms.',
    image: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=800&q=80',
    tags: ['RAP', 'SIA', 'World Bank ESF', 'IFC Standards'],
    features: [
      'Preparation of Resettlement Action Plans (RAPs)',
      'Livelihood restoration and compensation frameworks',
      'Stakeholder engagement and community consultation',
      'Social Impact Assessments (SIA) and mitigation planning',
      'Grievance redress mechanisms and monitoring',
      'Alignment with World Bank ESF and IFC Performance Standards',
    ],
  },
  {
    id: 'research',
    icon: '🔬',
    title: 'Research & Baseline Studies',
    short: 'Research',
    description: 'Social, economic, and environmental baseline surveys with quantitative and qualitative data collection and GESI analyses.',
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&q=80',
    tags: ['GESI', 'Baseline Surveys', 'Policy Research', 'Labour Market'],
    features: [
      'Social, economic, and environmental baseline surveys',
      'Gender and Social Inclusion (GESI) analyses',
      'Labour market and employment studies',
      'Climate change adaptation and livelihood assessments',
      'Policy and institutional research',
      'Quantitative and qualitative data collection, analysis, and reporting',
    ],
  },
  {
    id: 'training',
    icon: '🎓',
    title: 'Training & Capacity Development',
    short: 'Training',
    description: 'OHS training, gender mainstreaming, institutional capacity strengthening, and bespoke corporate training programs.',
    image: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&q=80',
    tags: ['OHS Training', 'Gender', 'Corporate', 'Institutional'],
    features: [
      'Occupational health and safety training',
      'Gender mainstreaming and leadership skills development',
      'Institutional capacity strengthening',
      'Corporate training programs tailored to organizational needs',
      'Project design and proposal development',
      'Technical assistance for donor-funded initiatives',
    ],
  },
]

export const STATS = [
  { value: '500+', label: 'Customers Served' },
  { value: '15+', label: 'Years Experience' },
  { value: '1000+', label: 'Audits Completed' },
  { value: '50+', label: 'Dedicated Team' },
]

export const VALUES = [
  { icon: '🛡️', title: 'Integrity', desc: 'Conducting all engagements with honesty, transparency, and accountability.' },
  { icon: '⭐', title: 'Professionalism', desc: 'Delivering consistent quality and ethical standards across all assignments.' },
  { icon: '💡', title: 'Innovation', desc: 'Applying creative, technological, and data-driven approaches to problem-solving.' },
  { icon: '🤝', title: 'Inclusivity', desc: 'Ensuring equal opportunities and representation across gender, youth, and ability.' },
  { icon: '🌱', title: 'Sustainability', desc: 'Encouraging energy efficiency and environmentally responsible practices.' },
  { icon: '🔗', title: 'Partnership', desc: 'Building long-term collaborative relationships for mutual growth.' },
  { icon: '🏆', title: 'Excellence', desc: 'Striving for superior performance and client satisfaction.' },
]

export const CLIENTS = [
  { name: 'GIZ Kenya', icon: '🌍' },
  { name: 'Aga Khan Foundation', icon: '🌟' },
  { name: 'Regen Organics', icon: '♻️' },
  { name: 'Kenya Ports Authority', icon: '⚓' },
  { name: "L'Oréal East Africa", icon: '💎' },
  { name: 'BSP Engineering', icon: '🏭' },
  { name: 'Jaman Engineering', icon: '⚙️' },
  { name: 'World Bank', icon: '🏦' },
]

export const ENGAGEMENTS = [
  {
    num: '01',
    title: 'OHS Training — GIZ Kenya',
    client: 'GIZ Kenya',
    tags: ['Occupational Health & Safety'],
    desc: 'Delivered comprehensive Occupational Health and Safety training for GIZ Kenya, focusing on industrial and construction safety. The program covered risk assessment, emergency response protocols, and behavioral safety culture enhancement for workers and supervisors.',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80',
  },
  {
    num: '02',
    title: 'GESI Analysis — CE4HOW Project, Kakamega County',
    client: 'Regen Organics / Sanergy Inc.',
    tags: ['GESI Analysis', 'Kakamega County'],
    desc: 'Conducted a Gender and Social Inclusion Analysis (GESI) for the CE4HOW Project implemented by Regen Organics (Sanergy Inc.) in Kakamega County. Assessed gender dynamics, social barriers, and inclusion gaps to inform project design.',
    image: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=800&q=80',
  },
  {
    num: '03',
    title: "Women's Economic Empowerment — Blue Economy Study",
    client: 'GIZ Kenya',
    tags: ['Gender Research', 'Blue Economy', '6 Coastal Counties'],
    desc: "Conducted a comprehensive study on Women's Economic Empowerment in the Blue Economy across six coastal counties for GIZ Kenya. The research examined livelihood opportunities, access to resources, and barriers faced by women in coastal and marine sectors.",
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
  },
  {
    num: '04',
    title: 'Civil Society Capacity Strengthening — AGECS Project',
    client: 'Aga Khan Foundation (AKF)',
    tags: ['Capacity Building', 'Gender Equality'],
    desc: 'Supported civil society capacity strengthening under the Advancing Gender Equality through Civil Society (AGECS) project by the Aga Khan Foundation (AKF). Delivered training and institutional strengthening activities to enhance CSO effectiveness.',
    image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80',
  },
  {
    num: '05',
    title: 'M&E Support — Industrial Safety & Training Programs',
    client: 'Multiple Clients',
    tags: ['MEAL', 'Industrial Safety'],
    desc: 'Provided Monitoring and Evaluation support for industrial safety and training programs, including development of performance frameworks, data collection systems, and impact documentation tools to track safety outcomes and training effectiveness.',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
  },
  {
    num: '06',
    title: 'Energy Efficiency & Maintenance Advisory',
    client: 'Jaman Engineering Works Ltd',
    tags: ['Energy Audit', 'Industrial'],
    desc: 'Delivered energy efficiency and maintenance advisory services in partnership with Jaman Engineering Works Ltd for multiple industrial clients. Included energy audits, efficiency roadmaps, and identification of technology upgrade opportunities.',
    image: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&q=80',
  },
]

export const STANDARDS = [
  { icon: '🏅', title: 'ISO 9001:2015', desc: 'Quality Management System Certified' },
  { icon: '⚙️', title: 'ISO 45001:2018', desc: 'Occupational Health & Safety Management' },
  { icon: '🌿', title: 'ISO 14001', desc: 'Environmental Management System' },
  { icon: '⚡', title: 'EPRA Compliant', desc: 'Energy & Petroleum Regulatory Authority Kenya' },
  { icon: '🌍', title: 'World Bank ESF', desc: 'Environmental & Social Framework' },
  { icon: '📋', title: 'IFC Standards', desc: 'IFC Performance Standards Aligned' },
]

export const TEAM_ROLES = [
  { initials: 'OHS', title: 'OHS Specialists', role: 'Safety Experts', desc: 'Certified occupational health & safety professionals with ISO 45001 expertise.' },
  { initials: '⚡', title: 'Energy Engineers', role: 'Energy Auditing', desc: 'EPRA-registered energy auditors and environmental engineering specialists.' },
  { initials: 'M&E', title: 'M&E Analysts', role: 'Monitoring & Evaluation', desc: 'Expert evaluators with deep experience in MEAL systems and data science.' },
  { initials: 'GS', title: 'GESI Specialists', role: 'Gender & Inclusion', desc: 'Gender mainstreaming and social inclusion experts for development programs.' },
  { initials: 'RAP', title: 'Social Safeguards', role: 'RAP & SIA Experts', desc: 'Resettlement planning specialists aligned with World Bank and IFC standards.' },
  { initials: '📊', title: 'Data Scientists', role: 'Digital & Data Tools', desc: 'Technology experts building digital M&E dashboards and data systems.' },
  { initials: '🏗️', title: 'Engineers', role: 'Infrastructure & Dev', desc: 'Engineering specialists from parent company Jaman Engineering Works Ltd.' },
  { initials: '📚', title: 'Trainers', role: 'Capacity Building', desc: 'Experienced facilitators delivering bespoke corporate and institutional training.' },
]
